### ISSUE TITLE
Which and where Fortran complier should I download to use?

### ISSUE THREAD

**Issue by wuxinwuyin** [oseledets/ttpy#78]
Dear developer:
I am a beginer in python. When I set up the toolbox of ttpy in Win10 by pip install and source code. a question appeared.That is error: f90 not supported by GnuFCompiler needed for tt\tt-fort\print\putstrmodule.F90. I think an unsuitable Fortran complier was used. So, I would like to know which Fortran complier should I use. Could you please give me a Fortran complier downloading address or send it to me or give me some advice for this issue?
Thank you for your attention. Best wishes to you.

**Comment by daskol** [comment]
I can't give you precise instruction how to build `ttpy` from scratch on Win10 since I have no access to any Windows workstation. Basically, there are multiple ways to get Fortran compler.

1. If you have access to [Intel Parallel Studio][1] distribution then you can just install Intel Fortran (ifort) as a part of the distirbution.

2. You could install [MinGW][2] or it fork [MinGW64][3] or another fork [CygWin][4]. All of them distribute Fortran as a part of GCC.

3. The last way to get Fortran I known is install software which replies on a Fortran. [Code::Blocks] IDE is an example.

I hope this short guide will be helpful for you.

[1]: https://software.intel.com/content/www/us/en/develop/tools/parallel-studio-xe.html
[2]: http://www.mingw.org/
[3]: http://mingw-w64.org/
[4]: https://cygwin.com/
[5]: https://codeblocks.org/

**Comment by bkmgit** [comment]
Try GFortran https://gcc.gnu.org/wiki/GFortran

Some other options listed at https://fortran-lang.org/compilers/
